name: CI/CD for AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Create or Update Lambda function
        run: |
          # Check if the function exists
          if aws lambda get-function --function-name lambda-autenticacao-tech-challenge; then
            echo "Function exists, updating..."
            aws lambda update-function-code \
              --function-name lambda-autenticacao-tech-challenge \
              --zip-file fileb://lambda_function.zip

            aws lambda update-function-configuration \
              --function-name lambda-autenticacao-tech-challenge \
              --vpc-config SubnetIds=subnet-0fb3bb4ae4e0b27b6,subnet-09c32234ebea3d3dd,subnet-0b47825759083e26d,subnet-0aa10a3ce65aa31ca,subnet-0b7d7186cd14229dc,subnet-004a5785aa1f8508f,SecurityGroupIds=sg-0b635a557830e706b
          else
            echo "Function does not exist, creating..."
            aws lambda create-function \
              --function-name lambda-autenticacao-tech-challenge \
              --runtime python3.9 \
              --role arn:aws:iam::123456789012:role/your-lambda-role \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://lambda_function.zip \
              --vpc-config SubnetIds=subnet-0fb3bb4ae4e0b27b6,subnet-09c32234ebea3d3dd,subnet-0b47825759083e26d,subnet-0aa10a3ce65aa31ca,subnet-0b7d7186cd14229dc,subnet-004a5785aa1f8508f,SecurityGroupIds=sg-0b635a557830e706b
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
