name: CI/CD for AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp lambda_function.py package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Deploy Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name autenticacao-tech-challenge-lambda \
            --zip-file fileb://lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1

      - name: Update Lambda function VPC configuration
        run: |
          aws lambda update-function-configuration \
            --function-name autenticacao-tech-challenge-lambda \
            --vpc-config SubnetIds=subnet-0fb3bb4ae4e0b27b6,subnet-09c32234ebea3d3dd,subnet-0b47825759083e26d,subnet-0aa10a3ce65aa31ca,subnet-0b7d7186cd14229dc,subnet-004a5785aa1f8508f,SecurityGroupIds=sg-0b635a557830e706b
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
